function symOut = costasLoop(symIn)

    disp("Costas Loop!")
    
    symOut = zeros(1,length(symIn));

    % Loop Filter
    Kp = 0.1;
    Ki = 0.1;
    e1 = 0;
    e2 = 0;
    integrator = 0;
    NCO_phase = 0;

    % NCO Gain
    Ko = 1.5;

    % Implement Costas Loop
    for i = 1:length(symIn)

        % signal generated by VCO
        symOut(i) = symIn(i) * exp(-1j*NCO_phase);

        % Phase difference, update e1
        e1 = imag(symOut(i)) * sign(real(symOut(i)));

        % Loop filter
        integrator = integrator + Ki*e1;
        e2 = Kp*e1+integrator;

        % symOut is the output of the NCO
        NCO_phase = NCO_phase + Ko*e2;

    end

end